development:
  CLIENT_API_HOST: 'http://localhost:4000'
  API_TOKEN: ''
  DATABASE_NAME:       'increase_development'
  DATABASE_USER:       'postgres'
  DATABASE_PASSWORD:   'postgres'
  DATABASE_HOST:       'localhost'
  DATABASE_PORT:       '5432'

test: 
  CLIENT_API_HOST: 'http://localhost:4000'
  API_TOKEN: ''
  DATABASE_NAME:       'increase_test'
  DATABASE_USER:       'postgres'
  DATABASE_PASSWORD:   'postgres'
  DATABASE_HOST:       'localhost'
  DATABASE_PORT:       '5432'